spring.application.name=PromoGamer

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.h2.console.enabled=true

spring.jpa.defer-datasource-initialization=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.hibernate.ddl-auto=none

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.address.email=${MY_EMAIL:pedronunes.dev67@gmail.com}
promogamer.whatsapp.group-number=${NUMBER_GROUP}

spring.security.user.name=${USERNAME_AUTHENTICATION}
spring.security.user.password=${USERNAME_PASSWORD}

evolution.api.key=${EVOLUTION_API_KEY}

spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.chat.options.temperature=0.7
