spring.application.name=PromoGamer

spring.datasource.url=jdbc:h2:mem:testdb;MODE=PostgreSQL
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true

spring.jpa.defer-datasource-initialization=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.hibernate.ddl-auto=none

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.address.email=${MY_EMAIL:pedronunes.dev67@gmail.com}
promogamer.whatsapp.group-number=${NUMBER_GROUP:fake-group-number}

spring.security.user.name=${USERNAME_AUTHENTICATION:test-user}
spring.security.user.password=${USERNAME_PASSWORD:test-password}

evolution.api.key=${EVOLUTION_API_KEY:fake-evolution-key}

spring.ai.openai.api-key=${OPENAI_API_KEY:fake-openai-key}
spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.chat.options.temperature=0.7